apiVersion: v1
kind: Namespace
metadata:
  name: a-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: a-server
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: tkdqja9573/service-a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: a-server
  labels:
    app: service-a
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: service-a
  type: ClusterIP