apiVersion: v1
kind: Namespace
metadata:
  name: b-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: b-server
  labels:
    app: service-b
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: tkdqja9573/service-b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: b-server
  labels:
    app: service-b
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: service-b
  type: ClusterIP