name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Build Docker Images
      run: |
        cd backend
        for dir in */ ; do
          cd $dir
          docker build -t myapp-${dir%/} .
          cd ..
        done

    - name: Deploy Docker Containers
      run: |
        cd backend
        for dir in */ ; do
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker stop myapp-${dir%/} || true && docker rm myapp-${dir%/} || true && docker run -d --name myapp-${dir%/} myapp-${dir%/}"
        done

  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Upload to Bunny CDN
      run: |
        cd frontend/dist
        lftp -c "set ftp:ssl-allow no; set ftp:passive-mode yes; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST_NAME }}; mirror -R . ./"